server:
  port: 8443

spring:
  # Thymeleaf缓存关闭
  thymeleaf:
    cache: false

  devtools:
    restart:
      # 目录中的源代码发生更改时， 重新启动应用程序
      additional-paths: src/main/java
      # 目录中的源代码发生更改时， 不需要重新启动应用程序
      exclude: static/**,public/**

  redis:
    database: 15
    host: 192.168.1.39
    port: 6379
    password: Redis!$13456
